name: PR workflow

on:
  workflow_call:

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print GH context
        run: |
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ github.event.pull_request.base.ref }}
